BlueModas/BlueModas/Models/Clientes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlueModas.Models
{
    public class Cliente
    {
        public long Id { get; set; }
        public string Nome { get; set; }
        public string e_mail { get; set; }
        public string telefone { get; set; }
    }
}

BlueModas/BlueModas/Controllers/ClientesController.cs
using BlueModas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BlueModas.Helpers;
using System.Net.Http;
using Newtonsoft.Json;

namespace BlueModas.Controllers
{
    public class ClientesController : Controller
    {
        private const string Cadastrar = @"~/Views/Clientes/Cadastro/Index.cshtml";
        private const string Fechar = @"~/Views/Pedidos/Fechar/Index.cshtml";

        // GET: CLientes
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Buscar(String Email)
        {
            Cliente cliente = new Cliente();

            var client = WebApiHttpClient.GetClient();
            client.BaseAddress = new Uri(client.BaseAddress + "api/Clientes/Buscar/" + Email);
            client.Timeout = TimeSpan.FromMinutes(10);
            HttpResponseMessage response = await client.GetAsync(client.BaseAddress);

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                cliente = JsonConvert.DeserializeObject<Cliente>(content);
                if (cliente.Id != 0)
                {
                    Pedidos pedido = Session["pedido"] != null ? (Pedidos)Session["pedido"] : new Pedidos();
                    pedido.cliente = cliente;
                    Session["pedido"] = pedido;
                    return View(Fechar, pedido);
                }
            }
            return View(Cadastrar);
        }

        public async Task<ActionResult> Incluir(String Nome, String Telefone, String Email)
        {
            Cliente cliente = new Cliente();

            var client = WebApiHttpClient.GetClient();
            client.BaseAddress = new Uri(client.BaseAddress + "api/Clientes");
            client.Timeout = TimeSpan.FromMinutes(10);
            HttpResponseMessage response = await client.GetAsync(client.BaseAddress);

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var produtos = JsonConvert.DeserializeObject<IEnumerable<Produtos>>(content);
                return Json(produtos, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

            //var client = WebApiHttpClient.GetClient();
            //client.BaseAddress = new Uri(client.BaseAddress + "api/Clientes/Buscar/" + Email);
            //client.Timeout = TimeSpan.FromMinutes(10);
            //HttpResponseMessage response = await client.GetAsync(client.BaseAddress);

            //if (response.IsSuccessStatusCode)
            //{
            //    string content = await response.Content.ReadAsStringAsync();
            //    cliente = JsonConvert.DeserializeObject<Cliente>(content);
            //    if (cliente.Id != 0)
            //    {
            //        Pedidos pedido = Session["pedido"] != null ? (Pedidos)Session["pedido"] : new Pedidos();
            //        pedido.cliente = cliente;
            //        Session["pedido"] = pedido;
            //        return View(Fechar, pedido);
            //    }
            //}
            //return View(Cadastrar);
        }
    }
}

BlueModas/BlueModas/Views/Clientes/Cadastro/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Blue Modas o seu espaço fashion.</p>

BlueModas/BlueModas/Views/Clientes/Cadastro/CadastrarCliente.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Novo Cliente</title>
</head>
<body>
    <div class="container login-container">
        <div class="col-md-6 login-form-2">
            <h3>Novo Cadastro:</h3>
            @using (Html.BeginForm("Incluir", "Clientes", FormMethod.Post))
            {
                <div class="form-group">
                    <label for="Nome" class="control-label">Nome</label>
                    <input id="Nome" class="form-control" placeholder="Digite seu nome completo" type="text"
                           data-error="Por favor, informe seu nome completo." required>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="form-group">
                    <label for="Telefone" class="control-label">Telefone</label>
                    <input id="Telefone" class="form-control" placeholder="Informe o seu telefone" type="tel"
                           data-error="Por favor, informe um telefone válido." required>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email</label>
                    <input id="Email" class="form-control" placeholder="Digite seu E-mail" type="email"
                           data-error="Por favor, informe um e-mail válido." required>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btnSubmit" value="Incluir" />
                </div>
            }
            </div>    
    </div>
</body>
</html>

BlueModas/BlueModas/Views/Clientes/Cadastro/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Rua Augusta<br />
    Piedade, SP 33.000-000<br />
    <abbr title="Phone">P:</abbr>
    (32) 99999-9999
</address>

<address>
    <strong>Suporte:</strong>   <a href="mailto:suporte@bluemodas.com.br">suporte@bluemodas.com.br</a><br />
    <strong>Contato:</strong> <a href="mailto:contato@bluemodas.com.br">contato@bluemodas.com.br</a>
</address>

BlueModas/BlueModas/Views/Clientes/Cadastro/Index.cshtml
@{
    ViewBag.Title = "Blue Modas";
}

<div style="margin-top:40px">
    @Html.Partial("CadastrarCliente")
</div>